orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    executor:
      name: android/android-machine
      tag: 2022.03.1
    steps:
      - checkout
      - android/restore-build-cache
      - android/restore-gradle-cache
      - run:
          name: Run Android tests
          command: ./gradlew androidApp:testDebugUnitTest
      - android/save-gradle-cache
      - android/save-build-cache

      - store_artifacts:
          path: androidApp/build/outputs/apk/debug